import type { StudioPreset, DatePickerStudioState } from "../types";

export const DEFAULT_DATE_PICKER_STATE: DatePickerStudioState = {
  "label": "Launch date",
  "description": "Pick a production launch date.",
  "helper": "Use native date constraints with accessible helper text.",
  "errorText": "Select a date inside the allowed range.",
  "successText": "Date is available.",
  "placeholder": "YYYY-MM-DD",
  "value": "2026-06-12",
  "min": "2026-01-01",
  "max": "2026-12-31",
  "step": 1,
  "id": "launch-date",
  "name": "launchDate",
  "title": "Launch date",
  "tabIndex": 0,
  "dir": "ltr",
  "lang": "en",
  "autocomplete": "bday",
  "inputMode": "numeric",
  "enterKeyHint": "done",
  "pickerType": "date",
  "calendarDensity": "balanced",
  "firstDayOfWeek": "monday",
  "showCalendarIcon": true,
  "showClearAction": true,
  "showHelper": true,
  "showSuccess": false,
  "required": true,
  "disabled": false,
  "readOnly": false,
  "invalid": false,
  "width": 420,
  "height": 118,
  "gap": 10,
  "padding": 18,
  "radius": 18,
  "borderWidth": 1,
  "borderStyle": "solid",
  "fontBucket": "google",
  "fontSearch": "",
  "systemFontIdx": 9,
  "googleFontFamily": "Inter",
  "fontSizeUnit": "px",
  "titleSize": 22,
  "bodySize": 14,
  "fontStyle": "normal",
  "textTransform": "none",
  "textDecoration": "none",
  "letterSpacing": 0,
  "letterSpacingUnit": "px",
  "lineHeight": 1.5,
  "radiusLinked": true,
  "radiusTL": 22,
  "radiusTR": 22,
  "radiusBR": 22,
  "radiusBL": 22,
  "shadowEnabled": true,
  "shadowX": 0,
  "shadowY": 8,
  "shadowBlur": 24,
  "shadowSpread": 0,
  "shadowOpacity": 0.25,
  "shadowColor": "#000000",
  "focusRingEnabled": true,
  "focusRingWidth": 2,
  "focusRingOffset": 2,
  "focusRingColor": "#38bdf8",
  "transitionDuration": 200,
  "transitionEasing": "ease",
  "background": "#0f172a",
  "foreground": "#e5eefb",
  "muted": "#94a3b8",
  "accent": "#38bdf8",
  "border": "#334155",
  "labelSize": 15,
  "inputSize": 16,
  "fontWeight": 650,
  "focusRing": 3,
  "previewState": "default"
};

export const DATE_PICKER_PRESETS: StudioPreset[] = [
  {
    "id": "premium-glass-compact",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "premium",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-glass-spacious",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "premium",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-soft-compact",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "premium",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-soft-spacious",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "premium",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 28,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-crisp-compact",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "premium",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-crisp-spacious",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "premium",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-hero-compact",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "premium",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 30,
      "borderWidth": 2,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "premium-hero-spacious",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "premium",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 30,
      "borderWidth": 2,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-glass-compact",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "editorial",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-glass-spacious",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "editorial",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-soft-compact",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "editorial",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-soft-spacious",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "editorial",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 28,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-crisp-compact",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "editorial",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-crisp-spacious",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "editorial",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-hero-compact",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "editorial",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 30,
      "borderWidth": 2,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "editorial-hero-spacious",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "editorial",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 30,
      "borderWidth": 2,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-glass-compact",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "admin",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-glass-spacious",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "admin",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-soft-compact",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "admin",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-soft-spacious",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "admin",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 28,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-crisp-compact",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "admin",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-crisp-spacious",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "admin",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-hero-compact",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "admin",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 30,
      "borderWidth": 2,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "admin-hero-spacious",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "admin",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 30,
      "borderWidth": 2,
      "background": "#111827",
      "foreground": "#f9fafb",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-glass-compact",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "commerce",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-glass-spacious",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "commerce",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-soft-compact",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "commerce",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-soft-spacious",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "commerce",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 28,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-crisp-compact",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "commerce",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-crisp-spacious",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "commerce",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-hero-compact",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "commerce",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 30,
      "borderWidth": 2,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "commerce-hero-spacious",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "commerce",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 30,
      "borderWidth": 2,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-glass-compact",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "support",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-glass-spacious",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "support",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-soft-compact",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "support",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-soft-spacious",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "support",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 28,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-crisp-compact",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "support",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-crisp-spacious",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "support",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-hero-compact",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "support",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 30,
      "borderWidth": 2,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "support-hero-spacious",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "support",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 30,
      "borderWidth": 2,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-glass-compact",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "system",
      "saas",
      "glass",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-glass-spacious",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "system",
      "saas",
      "glass",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-soft-compact",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "system",
      "editorial",
      "soft",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 28,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-soft-spacious",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "system",
      "editorial",
      "soft",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 28,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-crisp-compact",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "system",
      "admin",
      "crisp",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-crisp-spacious",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "system",
      "admin",
      "crisp",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-hero-compact",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "system",
      "commerce",
      "hero",
      "compact",
      "reduced-motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 330,
      "height": 118,
      "gap": 8,
      "padding": 16,
      "radius": 30,
      "borderWidth": 2,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  },
  {
    "id": "system-hero-spacious",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "system",
      "commerce",
      "hero",
      "spacious",
      "motion",
      "export-safe"
    ],
    "state": {
      "label": "Launch date",
      "description": "Pick a production launch date.",
      "helper": "Use native date constraints with accessible helper text.",
      "errorText": "Select a date inside the allowed range.",
      "successText": "Date is available.",
      "placeholder": "YYYY-MM-DD",
      "value": "2026-06-12",
      "min": "2026-01-01",
      "max": "2026-12-31",
      "step": 1,
      "id": "launch-date",
      "name": "launchDate",
      "title": "Launch date",
      "tabIndex": 0,
      "dir": "ltr",
      "lang": "en",
      "autocomplete": "bday",
      "inputMode": "numeric",
      "enterKeyHint": "done",
      "pickerType": "date",
      "calendarDensity": "balanced",
      "firstDayOfWeek": "monday",
      "showCalendarIcon": true,
      "showClearAction": true,
      "showHelper": true,
      "showSuccess": false,
      "required": true,
      "disabled": false,
      "readOnly": false,
      "invalid": false,
      "width": 460,
      "height": 118,
      "gap": 18,
      "padding": 28,
      "radius": 30,
      "borderWidth": 2,
      "background": "#18181b",
      "foreground": "#fafafa",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "labelSize": 15,
      "inputSize": 16,
      "fontWeight": 650,
      "focusRing": 3,
      "previewState": "default"
    }
  }
];
